spring:
  redis:
    database: 1
    host: ${redis_db.ip}
    port: ${redis_db.port}
    password: ${redis_db.password}
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0