spring:
  application:
    name: customize-generator
  profiles:
    include:
      - druid
      - mybatis
      - generator
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 9001
  servlet:
    context-path: /customize-generator
    session:
      timeout: 60s
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
  # 16 * 1024
  max-http-header-size: 16384