spring:
  application:
    name: teaching-hbase-client

server:
  port: 9000
  servlet:
    context-path: /teaching/hbase
    session:
      timeout: 60s
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
  max-http-header-size: 20480


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#      defaultZone: http://eureka.didispace.com/eureka/

---
HBase:
  nodes: 192.168.0.108
#  nodes: 192.168.1.214
  maxSize: 524288000