spring:
  application:
    name: teaching-web
  profiles:
    active: pro
    include:
      - druid
      - mybatis
      - redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  messages:
    basename: i18n/messages

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

feign:
  client:
    config:
      remote-service:
        connectTimeout: 30000

---
logging:
  config: classpath:log4j2.yml
