server:
  port: 8080
  context-path: /dev/teaching
  session:
    timeout: 60
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000

---
spring:
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**
  thymeleaf:
    cache: false
  mvc:
    favicon:
      enabled: false

---
eureka:
  client:
    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/
      defaultZone: http://eureka.didispace.com/eureka/

---
server_url:
  localhost: 127.0.0.1
  ip: ${server_url.localhost}


redis_db:
  url: ${server_url.ip}

mysql_db:
  url: jdbc:mysql://${server_url.ip}:3306/teaching?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&noAccessToProcedureBodies=true
  username: teaching
  password: 123456