server:
  port: 8080
  context-path: /teaching
  session:
    timeout: 60
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000

---
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

---
mysql_db:
  url: jdbc:mysql://127.0.0.2:3306/teaching?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&noAccessToProcedureBodies=true
  username: teaching
  password: 123456