server:
  port: 8080
  servlet:
    context-path: /dev/teaching
    session:
      timeout: 60s
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
---
spring:
  devtools:
    restart:
      enabled: true
      exclude: WEB-INF/**
  thymeleaf:
    cache: false
  mvc:
    favicon:
      enabled: false
---