spring:
  application:
    name: customize-hbase-client
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 9000
  servlet:
    context-path: /customize/hbase
    session:
      timeout: 60s
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
  # 16 * 1024
  max-http-header-size: 16384


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#      defaultZone: http://eureka.didispace.com/eureka/

---
HBase:
#  nodes: 192.168.0.108
  nodes: 192.168.1.214
  maxSize: 524288000