# http client连接池
httpclient:
  pool:
    # 最大连接数
    maxTotal: 200
    # 路由基础连接
    defaultMaxPerRoute: 20
    # 连接超时时间，单位毫秒
    connectTimeout: 10000
    # http client中从connection pool中获得一个connection的超时时间,单位毫秒
    connectionRequestTimeout: 500
    # 请求获取数据的超时时间，单位毫秒。如果访问一个接口，多少时间内无法返回数据，就直接放弃此次调用
    socketTimeout: 15000
    staleConnectionCheckEnabled: true
    # 可用空闲连接过期时间,重用空闲连接时会先检查是否空闲时间超过这个时间，如果超过，释放socket重新建立
    validateAfterInactivity: 30000

cfsc:
  selectUserList: http://127.0.0.1:8005/cfsoc-cfsc/