mybatis:
  typeAliasesPackage: com.customize.manage.entity
  mapperLocations: classpath:mapper/*Mapper.xml, classpath:mapper/core/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
---
pagehelper:
  helper-dialect: mysql
  params: count=countSql
---
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
