spring:
  application:
    name: customize-manage
  profiles:
    active: dev
    include:
      - druid
      - mybatis
      - quartz
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 10MB

--- # tomcat 配置
server:
  port: 8080
  servlet:
    context-path: /customize-manage
    session:
      timeout: 60s
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
  # 16 * 1024
  max-http-header-size: 16384

--- # eureka 基本配置
eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.cloud.client.ip-address}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: ${eureka_defaultZone}

--- # feign 配置
feign:
  httpclient:
    connection-timeout: 60000
  hystrix:
    enabled: true

--- # hystrix 配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

--- # ribbon 配置
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

--- # log4j2 配置
logging:
  config: classpath:log/log4j2.yml
