--- # eureka 服务端地址
eureka_defaultZone: http://127.0.0.1:8761/eureka
#eureka_defaultZone: http://eureka.didispace.com/eureka/

--- # mysql 配置
mysql_db:
  url: jdbc:mysql://127.0.0.1:3306/enterprise?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&noAccessToProcedureBodies=true
  username: enterprise
  password: 123456